/*
 * This source file was generated by the Gradle 'init' task
 */
package test;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.event.MouseEvent;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCreatesFreightDispatchGame() {
        App classUnderTest = new App();
        assertInstanceOf(RailwayGamePanel.class, classUnderTest.createGamePanel());
        assertTrue(classUnderTest.getTitle().contains("Last Mile"));
    }

    @Test void dispatchScreenRendersItsStarterNetwork() {
        RailwayGamePanel game = new App().createGamePanel();
        game.setSize(1440, 900);
        assertEquals(5, game.world.stations.size());
        assertEquals(4, game.world.contracts.size());
        assertEquals(RailwayWorld.ContractState.IN_TRANSIT, game.world.contracts.get(0).state);

        BufferedImage image = new BufferedImage(1440, 900, BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = image.createGraphics();
        game.paint(graphics);
        graphics.dispose();
        assertEquals(new java.awt.Color(27, 42, 42).getRGB(), image.getRGB(10, 10));
    }

    @Test void bookButtonOpensNavigableMechanicGuide() {
        RailwayGamePanel game = new App().createGamePanel();
        game.setSize(1440, 900);

        click(game, 940, 40);
        assertTrue(game.guideOpen);

        click(game, 300, 255);
        assertEquals(RailwayGamePanel.GuideTopic.TRACK, game.guideTopic);

        BufferedImage image = new BufferedImage(1440, 900, BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = image.createGraphics();
        game.paint(graphics);
        graphics.dispose();
        assertEquals(new java.awt.Color(27, 42, 42).getRGB(), image.getRGB(230, 160));

        click(game, 1190, 164);
        assertFalse(game.guideOpen);
    }

    @Test void dispatchBoardAcceptsAVisibleFreightOrder() {
        RailwayGamePanel game = new App().createGamePanel();
        game.setSize(1200, 800);
        MouseEvent clickAccept = new MouseEvent(game, MouseEvent.MOUSE_PRESSED,
            System.currentTimeMillis(), 0, 1145, 340, 1, false, MouseEvent.BUTTON1);

        for (var listener : game.getMouseListeners()) {
            listener.mousePressed(clickAccept);
        }

        assertEquals(RailwayWorld.ContractState.ACCEPTED, game.world.contracts.get(1).state);
    }

    @Test void resizedWindowKeepsTheGameAspectRatio() {
        RailwayGamePanel game = new App().createGamePanel();
        game.setSize(1200, 800);
        BufferedImage image = new BufferedImage(1200, 800, BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = image.createGraphics();
        game.paint(graphics);
        graphics.dispose();

        assertEquals(new java.awt.Color(245, 245, 234).getRGB(), image.getRGB(10, 10));
        assertEquals(new java.awt.Color(27, 42, 42).getRGB(), image.getRGB(10, 30));
    }

    @Test void timetableButtonsReorderStopsAndToggleRepeating() {
        RailwayGamePanel game = new App().createGamePanel();
        game.setSize(1440, 900);
        RailwayWorld.Train train = game.world.trains.get(0);
        RailwayWorld.Node activeDestination = train.destination;

        click(game, 60, 337);
        click(game, 692, 576);
        click(game, 1080, 576);
        click(game, 562, 378);
        assertEquals(5, train.stops.size());

        click(game, 157, 657);
        assertEquals(new RailwayWorld.Node(1325, 760), train.stops.get(2));
        assertEquals(activeDestination, train.destination);

        click(game, 60, 708);
        assertFalse(train.looping);

        click(game, 197, 594);
        assertEquals(4, train.stops.size());
        assertEquals(activeDestination, train.destination);
    }

    @Test void scheduledFreightDeliveryPaysItsContract() {
        RailwayWorld world = new RailwayWorld();
        RailwayWorld.Contract contract = world.contracts.get(0);
        int startingCash = world.cash;

        assertEquals(RailwayWorld.ContractState.IN_TRANSIT, contract.state);
        assertEquals(6, world.trains.get(0).load());

        world.advanceTicks(130);

        assertEquals(RailwayWorld.ContractState.COMPLETE, contract.state);
        assertEquals(1, world.deliveries);
        assertEquals(startingCash + contract.reward, world.cash);
    }

    @Test void stationsCanBeBuiltAwayFromRailsAndConnectedLater() {
        RailwayWorld world = new RailwayWorld();
        RailwayWorld.Node siding = new RailwayWorld.Node(1800.25, 1250.75);

        RailwayWorld.Station station = world.buildStation(siding);

        assertNotNull(station);
        assertEquals(siding, station.position);
        assertTrue(world.buildTrack(siding, new RailwayWorld.Node(1990.5, 1300.25)));
        assertTrue(world.stations.contains(station));
    }

        @Test void demolitionRefundsUnusedObjectsAndProtectsAssetsInUse() {
        RailwayWorld world = new RailwayWorld();
        RailwayWorld.Train firstTrain = world.trains.get(0);
        int startingCash = world.cash;

        assertEquals(RailwayWorld.DemolitionResult.TRACK_IN_USE,
            world.demolishAt(new RailwayWorld.Node(350, 440), 2));
        assertEquals(RailwayWorld.DemolitionResult.STATION_IN_USE,
            world.demolishAt(new RailwayWorld.Node(175, 440), 2));

        RailwayWorld.Node sidingPosition = new RailwayWorld.Node(1800, 1500);
        RailwayWorld.Station siding = world.buildStation(sidingPosition);
        assertNotNull(siding);
        assertEquals(RailwayWorld.DemolitionResult.STATION_REMOVED,
            world.demolishAt(sidingPosition, 2));
        assertFalse(world.stations.contains(siding));
        assertEquals(startingCash - RailwayWorld.STATION_COST + RailwayWorld.STATION_COST / 2, world.cash);

        RailwayWorld.Node lineStart = new RailwayWorld.Node(1800, 1500);
        RailwayWorld.Node lineEnd = new RailwayWorld.Node(2000, 1500);
        assertTrue(world.buildTrack(lineStart, lineEnd));
        RailwayWorld.Node signal = new RailwayWorld.Node(1900, 1500);
        assertTrue(world.toggleSignal(signal));
        assertEquals(RailwayWorld.DemolitionResult.SIGNAL_REMOVED, world.demolishAt(signal, 2));
        assertFalse(world.signals.contains(signal));
        assertEquals(RailwayWorld.DemolitionResult.TRACK_REMOVED, world.demolishAt(signal, 2));

        RailwayWorld.Train secondTrain = world.deployTrain(new RailwayWorld.Node(400, 440));
        assertNotNull(secondTrain);
        assertEquals(RailwayWorld.DemolitionResult.TRAIN_CARRYING_CARGO,
            world.demolishTrain(firstTrain));
        assertEquals(RailwayWorld.DemolitionResult.TRAIN_REMOVED, world.demolishTrain(secondTrain));
        assertEquals(RailwayWorld.DemolitionResult.LAST_TRAIN, world.demolishTrain(firstTrain));
        }

        @Test void demolitionToolRemovesASelectedTrackSection() {
        RailwayGamePanel game = new App().createGamePanel();
        game.setSize(1440, 900);
        RailwayWorld.Node start = new RailwayWorld.Node(970, 160);
        RailwayWorld.Node end = new RailwayWorld.Node(1110, 160);
        assertTrue(game.world.addTrack(start, end));
        int trackCount = game.world.tracks.size();

        click(game, 60, 387);
        click(game, 903, 204);

        assertEquals(trackCount - 1, game.world.tracks.size());
        }

    @Test void oneShotScheduleStopsAfterItsLastStation() {
        RailwayWorld world = new RailwayWorld();
        RailwayWorld.Train train = world.trains.get(0);

        assertTrue(world.addScheduleStop(train, world.stations.get(1)));
        assertTrue(world.addScheduleStop(train, world.stations.get(3)));
        assertTrue(world.addScheduleStop(train, world.stations.get(4)));
        assertTrue(world.moveScheduleStop(train, 4, -1));
        assertEquals(new RailwayWorld.Node(1325, 760), train.stops.get(3));
        assertEquals(new RailwayWorld.Node(1010, 440), train.destination);
        assertTrue(world.removeScheduleStop(train, 0));
        assertEquals(new RailwayWorld.Node(1010, 440), train.destination);
        world.setScheduleLoop(train, false);

        world.advanceTicks(550);

        assertFalse(train.looping);
        assertTrue(train.path.isEmpty());
        assertEquals(new RailwayWorld.Node(700, 760), train.position);
    }

    @Test void reverseFacingTrainSpritesStayUpright() {
        assertTrue(RailwayGamePanel.needsHorizontalFlip(Math.PI));
        assertEquals(0, RailwayGamePanel.uprightHeading(Math.PI), 0.0001);
        assertTrue(RailwayGamePanel.needsHorizontalFlip(-Math.PI));
        assertEquals(0, RailwayGamePanel.uprightHeading(-Math.PI), 0.0001);
        assertFalse(RailwayGamePanel.needsHorizontalFlip(0));
    }

    @Test void carriagesFollowRailThroughAStationCorner() {
        RailwayWorld world = new RailwayWorld();
        RailwayWorld.Train train = world.trains.get(0);
        assertTrue(world.addScheduleStop(train, world.stations.get(3)));
        assertTrue(world.moveScheduleStop(train, 1, 1));

        world.advanceTicks(102);

        assertEquals(new RailwayWorld.Node(1010, 440), train.position);
        assertEquals(new RailwayWorld.Node(700, 760), train.destination);
        RailwayGamePanel renderer = new App().createGamePanel();
        for (int index = 1; index <= train.carriages; index++) {
            double[] carriage = renderer.carriagePosition(train, index);
            assertTrue(distanceFromRail(world, carriage[0], carriage[1]) < 0.0001,
                    "carriage " + index + " should stay on a rail at the station turn");
        }

        world.advanceTicks(10);
        for (int index = 1; index <= train.carriages; index++) {
            double[] carriage = renderer.carriagePosition(train, index);
            assertTrue(distanceFromRail(world, carriage[0], carriage[1]) < 0.0001,
                    "carriage " + index + " should follow the curved route");
        }
    }

    @Test void saveRestoresMovingTrainsContractsAndMapView(@TempDir Path tempDirectory)
            throws java.io.IOException {
        RailwayWorld world = new RailwayWorld();
        RailwayWorld.Train train = world.trains.get(0);
        RailwayWorld.Contract contract = world.contracts.get(1);
        assertTrue(world.acceptContract(contract));
        assertTrue(world.addScheduleStop(train, world.stations.get(3)));
        assertTrue(world.addCarriage(train));
        world.setScheduleLoop(train, false);
        world.advanceTicks(17);
        RailwayWorld.ViewState view = new RailwayWorld.ViewState(420.5, 180.25, 0.74,
                train.id, contract.id, false, true);
        Path savePath = tempDirectory.resolve("railway.lmsave");

        world.save(savePath, view);
        RailwayWorld.LoadedGame loaded = RailwayWorld.load(savePath);
        RailwayWorld restored = loaded.world();
        RailwayWorld.Train restoredTrain = restored.trains.get(0);

        assertEquals(world.cash, restored.cash);
        assertEquals(world.day, restored.day);
        assertEquals(world.minutes, restored.minutes);
        assertEquals(world.tracks, restored.tracks);
        assertEquals(train.stops, restoredTrain.stops);
        assertEquals(train.railTrail, restoredTrain.railTrail);
        assertEquals(train.positionAt(), restoredTrain.positionAt());
        assertEquals(train.load(), restoredTrain.load());
        assertSame(restored.contracts.get(0), restoredTrain.cargo.get(0).contract());
        assertEquals(RailwayWorld.ContractState.ACCEPTED, restored.contracts.get(1).state);
        assertEquals(view, loaded.view());

        world.advanceTicks(20);
        restored.advanceTicks(20);
        assertEquals(train.positionAt(), restoredTrain.positionAt());
        assertEquals(world.cash, restored.cash);
    }

    private static void click(RailwayGamePanel panel, int x, int y) {
        MouseEvent event = new MouseEvent(panel, MouseEvent.MOUSE_PRESSED,
                System.currentTimeMillis(), 0, x, y, 1, false, MouseEvent.BUTTON1);
        for (var listener : panel.getMouseListeners()) {
            listener.mousePressed(event);
        }
    }

    private static double distanceFromRail(RailwayWorld world, double x, double y) {
        double nearest = Double.POSITIVE_INFINITY;
        for (RailwayWorld.Edge edge : world.tracks) {
            double dx = edge.second().x() - edge.first().x();
            double dy = edge.second().y() - edge.first().y();
            double lengthSquared = dx * dx + dy * dy;
            double fraction = ((x - edge.first().x()) * dx + (y - edge.first().y()) * dy)
                    / lengthSquared;
            fraction = Math.max(0, Math.min(1, fraction));
            double px = edge.first().x() + fraction * dx;
            double py = edge.first().y() + fraction * dy;
            nearest = Math.min(nearest, Math.hypot(x - px, y - py));
        }
        return nearest;
    }
}
